<?php


namespace vloop\problems\tables;


use vloop\problems\tables\query\BaseQuery;
use yii\db\ActiveRecord;

/**
 * Class TableReports
 * @package vloop\problems\tables
 * @property int $id [int(11)]
 * @property int $user_id [int(11)]
 * @property int $problem_id [int(11)]
 * @property string $description [varchar(255)]
 */
class TableReports extends ActiveRecord
{
    public static function find()
    {
        return new BaseQuery(get_called_class());
    }

    public static function tableName()
    {
        return 'vloop_reports'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['user_id', 'problem_id', 'description'], 'required'],
            [['description', ], 'unique', 'targetAttribute' => ['problem_id', 'user_id', 'description']],
            [['problem_id', ], 'unique', 'targetAttribute' => ['problem_id', 'user_id']],
            ['problem_id', 'exist', 'targetClass' => TableProblems::className(), 'targetAttribute' => 'id'],

        ];
    }

}