<?php


namespace vloop\problems\entities\forms;


use vloop\problems\entities\interfaces\Form;
use yii\base\Model;

class FormReport extends Model implements Form
{

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function validatedFields(): array
    {
        // TODO: Implement validatedFields() method.
    }
}